# Generated by Django 5.1.1 on 2024-09-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='reversed',
            field=models.BooleanField(default=False, help_text="The vote is reversed (excluded from count and average) if it's detected as fraudulent", verbose_name='Reversed'),
        ),
    ]
